name: "Steampipe GitHub Action"
author: "Turbot.com"
description: "Set up a specific version of Steampipe"

branding:
  color: "red"
  icon: "shield"

inputs:
  version:
    description: Version of Steampipe that will be installed.
    required: false
    default: latest
  run:
    description: A list of benchmarks and controls to run (comma-separated). If left blank, `all` controls and benchmarks are run.
    required: false
    default: ""
  directory:
    description: Directory to run the scan on, from the repo root. Default is `.` (root of the repository).
    required: false
    default: "."
  mod:
    description: Git clone URL of a steampipe mod that will be installed.
    required: true
  output:
    description: Select a console output format i.e. brief, csv, html, json, md, text or none.
    required: false
    default: text
  export:
    description: "Export output to files in various output formats such as csv, html, json, md, nunit3 or asff (json) - comma separated."
    required: false
    default: ""
  where:
    description: SQL 'where' clause, or named query, used to filter controls
    required: false
    default: ""
  github-token:
    description: "the token is used for fetching patch of a pull request to show only new issues"
    default: ${{ github.token }}
    required: false

runs:
  using: node16
  main: dist/index.js
