name: Run Steampipe Action
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run local Action
        uses: ./
        with:
          connection_config: |
            connection "terraform" {
              plugin = "terraform"
              paths = ["examples/terraform/aws/**/*.tf"] # Provide the path to terraform files
            }
          plugins: terraform
          mod: "https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git"
          export: summary.md
          run: control.ec2_ebs_default_encryption_enabled
      - name: Save to summary
        run: |
          cat summary.md > $GITHUB_STEP_SUMMARY
          rm -rf summary.md
