name: Run Steampipe
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local my-action
        uses: ./
        continue-on-error: true
        with:
          version: latest
          connection_config: |
            connection "terraform" {
              plugin = "terraform"
              paths = ["examples/terraform/aws/**/*.tf"] # Provide the path to terraform files
            }
          plugins: terraform
          mod: 'https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git'
          export: "./check_output.md"
      - name: Check terraform compliance health
        id: terraform-compliance-health
        run: |
          cat ./check_output.md >> $GITHUB_STEP_SUMMARY
