name: Run Steampipe Checks
on:
  push:
    branches:
      - action-kp
  pull_request:
  workflow_dispatch:

jobs:
  steampipe-terraform-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Steampipe terraform scan action
        continue-on-error: false
        uses: ./
        with:
          version: 'latest'
          connection_config: |
            connection "terraform" {
              plugin = "terraform"
              paths = ["examples/terraform/aws/**/*.tf"]
            }
          plugins: terraform
          mod: 'https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git'
          export: export-jsn.json
