name: Test workflow Lalit
on:
  push:
    branches:
      - first-setup-lalit
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local my-action
        continue-on-error: true
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          version: "latest"
          export: "./github_checker_output.md"
          connection_config: |
            connection "github" {
              plugin = "github"
              # paths = [ "" ]
            }
          plugins: "github"
          # mod: "https://github.com/turbot/steampipe-utils.git"
          mod: "."
          
      - name: Check repository health
        id: check-repository-health
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cat ./github_checker_output.md >> $GITHUB_STEP_SUMMARY
