name: Test workflow
on:
  push:
    branches:
      - first-setup
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Use local my-action
        uses: ./
        with:
          version: 'latest'
          connection_config: |
            connection "terraform" {
              plugin = "terraform"
              paths = [ "test_dir/ec2/*.tf" ]
            }
          plugins: "[\"terraform\"]"
          mod: 'https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git'
